package it.tinna.smartdoc.shared.constants;

public class ISharedConstants {

    public static String CONFIG_DOMAIN_GLOBAL = "GLOBAL";
    public static String CONFIG_DOMAIN_DOCUMENTI = "DOCUMENTI";
    public static String CONFIG_DOMAIN_ARTICOLI = "ARTICOLI";
    public static String CONFIG_DOMAIN_CLIENTI = "CLIENTI";
    public static String CONFIG_DOMAIN_FORNITORI = "FORNITORI";
    public static String CONFIG_DOMAIN_STAMPA = "PRINT";

    public static String CONFIGURAZIONE_DOMINIO_STAMPA = "PRINT";
    public static String CONFIG_KEY_STAMPA_AGENTE = "STAMPA_AGENTE";
    
    // Alias for legacy compatibility
    public static String CONFIGURAZIONE_DOMINIO_ARTICOLI = CONFIG_DOMAIN_ARTICOLI;

    public static String CONFIG_KEY_TIPOSTORE = "TIPO_STORE";
    public static String CONFIG_KEY_ABILITAPROGETTI = "PROGETTI";
    public static String CONFIG_KEY_ABILITANNOTAZIONIESTESE = "ANNOTAZIONI_ESTESE";
    public static String CONFIG_KEY_ABILITADIVISIONI = "DIVISIONI";
    public static String CONFIG_KEY_NUM_NOTE_DEBITO_FATTURE = "NUMERAZIONE_NOTE_DEBITO_UGUALE_FATTURE";
    public static String CONFIG_KEY_PARTICELLE = "PARTICELLE";
    
    public static String CONFIG_KEY_CLIENTI_ABILITA_DATICOMMERCIALI = "ABILITA_DATI_COMMERCIALI";
    public static String CONFIG_KEY_FORNITORI_ABILITA_DATICOMMERCIALI = "ABILITA_DATICOMMERCIALI";
    
    public static String CONFIGURAZIONE_CHIAVE_PREZZI_IVATI = "PREZZI_IVATI";
    public static String CONFIGURAZIONE_VENDITABANCO_IVA = "IVA_VENDITA_BANCO";
    
    // UI Configuration Keys
    public static String CONFIGURAZIONE_ABILITA_ALIQUOTEIVA_CHIAVE = "IMPOSTAZIONIDATI_ABILITA_ALIQUOTEIVA";
    public static String CONFIGURAZIONE_ABILITA_CATEGORIESPESA_CHIAVE = "IMPOSTAZIONIDATI_ABILITA_CATEGORIESPESA";
    public static String CONFIGURAZIONE_ABILITA_LISTINI_CHIAVE = "IMPOSTAZIONIDATI_ABILITA_LISTINI";
    public static String CONFIGURAZIONE_ABILITA_MAGAZZINI_CHIAVE = "IMPOSTAZIONIDATI_ABILITA_MAGAZZINI";
    public static String CONFIGURAZIONE_ABILITA_SOTTOCONTICLIENTI_CHIAVE = "IMPOSTAZIONIDATI_ABILITA_SOTTOCONTICLIENTI";
    public static String CONFIGURAZIONE_ABILITA_SOTTOCONTIARTICOLI_CHIAVE = "IMPOSTAZIONIDATI_ABILITA_SOTTOCONTIARTICOLI";
    public static String CONFIGURAZIONE_ABILITA_RISORSE_CHIAVE = "IMPOSTAZIONIDATI_ABILITA_RISORSE";
    public static String CONFIGURAZIONE_ABILITA_TIPIPAGAMENTO_CHIAVE = "IMPOSTAZIONIDATI_ABILITA_TIPIPAGAMENTO";
    public static String CONFIGURAZIONE_ABILITA_ZONECOMPETENZA_CHIAVE = "IMPOSTAZIONIDATI_ABILITA_ZONECOMPETENZA";

    public static String COMBOSMAP_KEY_DATIAZIENDA = "DATIAZIENDA";
    public static String COMBOSMAP_KEY_REGIMIFISCALI = "REGIMIFISCALI";
    public static String COMBOSMAP_KEY_ALIQUOTEIVA = "aliquoteIva";
    public static String COMBOSMAP_KEY_UNITAMISURA = "unitaMisura";
    public static String COMBOSMAP_KEY_PARTICELLE = "particelle";
    public static String COMBOSMAP_KEY_TIPIPAGAMENTO = "tipiPagamento";
    public static String COMBOSMAP_KEY_LISTINI = "listini";
    public static String COMBOSMAP_KEY_RISORSE = "risorse";
    public static String COMBOSMAP_KEY_MAGAZZINI = "magazzini";
    public static String COMBOSMAP_KEY_AGENTI = "agenti";
    public static String COMBOSMAP_KEY_PROGETTI = "progetti";
}
